/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taksitliUrunSatis;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sony
 */
public class Odeme extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form Odeme
     */
    public Odeme() {
        initComponents();
        try {
            cmbTaksit.addItem("1");
            cmbTaksit.addItem("2");
            cmbTaksit.addItem("3");
            cmbTaksit.addItem("4");
            cmbTaksit.addItem("5");
            

            jTable1.setModel(dtm);
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/URUNSATISDB", "sa", "as");
            String urunadi;
            int urunid;
            double fiyat;
            int adet;
            double aylik;
            int taksitSayisi;
            int odenentaksitsayisi;

            dtm.setColumnIdentifiers(new Object[]{"ID", "TOPLAMTUTAR", "AYLIKTAKSIT", "TAKSITSAYISI", "KALANTAKSITSAYISI"});
            Statement stm = con.createStatement();
            ResultSet rsm = stm.executeQuery("SELECT * FROM TAKSITLISATIS WHERE MUSTERIID=" + Musteri.id);
            while (rsm.next()) {
                urunid = rsm.getInt("ID");
                fiyat = rsm.getDouble("TOPLAMTUTAR");
                aylik = rsm.getDouble("AYLIKTAKSIT");
                taksitSayisi = rsm.getInt("TAKSITSAYISI");
                odenentaksitsayisi = rsm.getInt("ODENENTAKSITSAYISI");
                dtm.addRow(new Object[]{urunid, fiyat, aylik, taksitSayisi, odenentaksitsayisi});
            }
            
            /* 
            Connection c2=DriverManager.getConnection("jdbc:derby://localhost:1527/URUNSATISDB","sa","as");
            PreparedStatement ps=c2.prepareStatement("INSERT INTO TAKSITLISATIS (URUNID,URUNADI,FIYAT,ADET) VALUES (?,?,?,?)");
            while (rs.next()) {
                urunid = rs.getInt("URUNID");
                urunadi = rs.getString("URUNADI");
                fiyat = rs.getDouble("TUTAR");
                adet = rs.getInt("ADET");
                
                dtm.addRow(new Object[]{urunid, urunadi, fiyat, adet});
                
                
            }*/
//            Vector v = new Vector();
//            v.add("Toplam Tutar:");
//            v.add(null);
//            v.add(Musteri.odemeMiktari);
//            dtm.addRow(v);
            //BU KISIM YAPILACAK                          
//            if (Musteri.odemeSekli == "Taksit") {
//                dtm.addColumn("Kalan Taksit Sayisi");
//                for (int i = 0; i < dtm.getRowCount()-1; i++) {
//                    for (int j = 0; j < dtm.getColumnCount(); j++) {
//                        Vector w = new Vector();
//                        w.add(Musteri.taksitSayisi);
//                        dtm.setValueAt(w, i, 4);
//                        
//                    }
//                }
            //          }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblKalanTutar = new javax.swing.JLabel();
        Ode = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbTaksit = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("ODEMELERIM");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Kalan odeme tutariniz: ");

        Ode.setText("Ode");
        Ode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdeActionPerformed(evt);
            }
        });

        jLabel4.setText("Odeme yapmak istediginiz taksit sayisi: ");

        cmbTaksit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTaksitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblKalanTutar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cmbTaksit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Ode)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTaksit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKalanTutar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTaksitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTaksitActionPerformed
        // TODO add your handling code here:
        if (Musteri.odemeSekli == "Nakit") {
            this.dispose();
        } else {
            Musteri.odemeTaksitSayisi = Integer.parseInt(cmbTaksit.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbTaksitActionPerformed

    private void OdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdeActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/URUNSATISDB", "sa", "as");
            Statement st = con.createStatement();
            String q = "SELECT * FROM TAKSITLISATIS WHERE ID=";
            int id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());

            ResultSet rs = st.executeQuery(q + id);
            if (rs.next()) {
                    Musteri.odemeMiktari = rs.getDouble("TOPLAMTUTAR");
                    Musteri.aylikTaksit = rs.getDouble("AYLIKTAKSIT");
                    Musteri.taksitSayisi = rs.getInt("TAKSITSAYISI");
            }
            Musteri.odemeMiktari = Musteri.odemeMiktari - Musteri.aylikTaksit * Double.parseDouble(cmbTaksit.getSelectedItem().toString());
            Musteri.taksitSayisi = Musteri.taksitSayisi - Integer.parseInt(cmbTaksit.getSelectedItem().toString());
            EntityManagerFactory emf2 = Persistence.createEntityManagerFactory("ProjeBP2PU");
            EntityManager em2 = emf2.createEntityManager();
            for (int i = 0; i < dtm.getRowCount(); i++) {
                for (int j = 0; j < dtm.getColumnCount(); j++) {
                    dtm.setValueAt(Musteri.taksitSayisi, jTable1.getSelectedRow(), 4);
                }
            }

            EntityManagerFactory emf3 = Persistence.createEntityManagerFactory("ProjeBP2PU");
            EntityManager em3 = emf3.createEntityManager();
            Query q3 = em3.createQuery("update Taksitlisatis k set k.odenentaksitsayisi=:taksitSayisi");
            q3.setParameter("taksitSayisi", Musteri.taksitSayisi);
            em3.getTransaction().begin();
            q3.executeUpdate();
            em3.getTransaction().commit();

            EntityManagerFactory cvb = Persistence.createEntityManagerFactory("ProjeBP2PU");
            EntityManager bnm = cvb.createEntityManager();
            Query qr = bnm.createQuery("update Taksitlisatis k set k.toplamtutar=:tplmtutar");
            qr.setParameter("tplmtutar", Musteri.odemeMiktari);
            bnm.getTransaction().begin();
            qr.executeUpdate();
            bnm.getTransaction().commit();

            lblKalanTutar.setText(Musteri.odemeMiktari + " TL");

            if (Musteri.odemeMiktari == 0) {
                JOptionPane.showMessageDialog(this, "Odemeniz basariyla gerceklestirilmistir.");
                EntityManagerFactory dfg = Persistence.createEntityManagerFactory("ProjeBP2PU");
                EntityManager hjk = dfg.createEntityManager();
                Query qy = hjk.createQuery("delete Taksitlisatis k WHERE k.odenentaksitsayisi=0");
                hjk.getTransaction().begin();
                qy.executeUpdate();
                hjk.getTransaction().commit();
            } else if (Musteri.odemeMiktari < 0) {
                this.dispose();
            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_OdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Odeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Odeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Odeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Odeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Odeme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ode;
    private javax.swing.JComboBox<String> cmbTaksit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblKalanTutar;
    // End of variables declaration//GEN-END:variables
}
